### PR TITLE
[Segeda Oleksandr] Theory

### PR DESCRIPTION
**Pull request by GholemHub**

### CODE REVIEW

**Review by Bartosz666 — APPROVED** [review]

**Comment by ArsenEloglian** [comment]
@Bartosz666 
Why this PR has been approved if header is incorrect?

**Review by ArsenEloglian — CHANGES_REQUESTED** [review]
PR header needs fix

**Comment by GholemHub** [comment]
[Segeda Oleksandr] Theory

**Comment by GholemHub** [comment]
[Segeda Oleksandr] Theory

**Comment by GholemHub** [comment]
Try 2

**Review by ArsenEloglian — APPROVED** [review]

**Pull request merged**
