### PR TITLE
[Dominik Lesniewski] [Kuba Kern] Project, presentation, added UNDO

### PR DESCRIPTION
**Pull request by hanzo912**

### CODE REVIEW

**Review by KubaKern — APPROVED** [review]

**Comment by hanzo912** [comment]
We forgot to update the .jar and .exe files, gonna reopen PR soon.

**Review by KubaKern — DISMISSED** [review]

**Comment by hanzo912** [comment]
Done!

**Review by ArsenEloglian — CHANGES_REQUESTED** [review]
Please revert unnecessary changes.

**Comment by hanzo912** [comment]
All unnecessary changes reverted.

**Review by KubaKern — APPROVED** [review]

**Review by ArsenEloglian — APPROVED** [review]

**Pull request merged**
