### PR TITLE
[Oliferuk Artur] Lista obecnosci

### PR DESCRIPTION
**Pull request by Mamin-simpotiaga**

### CODE REVIEW

**Review by hanzo912 — APPROVED** [review]

**Review by GholemHub — DISMISSED** [review]
BAN

**Review by GholemHub — COMMENTED** [review]
BAN REBOOT LIST!!!

**Review by ArsenEloglian — CHANGES_REQUESTED** [review]
Needs work

**Review by GholemHub — APPROVED** [review]
SDOJNVEWJBV

**Pull request closed without merging**
